spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  session:
    store-type: redis # 세션 저장소 유형을 Redis로 설정
    redis:
      namespace: spring:session

react:
  server:
    front_url: http://localhost:3000

jwt:
  issuer: galijung0520@gmail.com # 이슈 발급자
  secret_key: study-springboot # 비밀키